version: "3.7"

networks:
  traefik_proxy:
    driver: bridge

services:
  traefik:
    container_name: traefik
    image: traefik:alpine
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    environment:
    labels:
      traefik.backend: traefik
      traefik.port: 8083
    networks:
      - traefik_proxy
    ports:
      - 443:443
      - 80:80
    expose:
      - 8083
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/ubuntu/configs/traefik/acme:/acme:rw
      - /home/ubuntu/configs/traefik/certs:/certs:rw
      - /home/ubuntu/configs/traefik/traefik.toml:/traefik.toml:rw

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Paris
    expose:
      - 9091
      - 51413
    labels:
      traefik.backend: transmission
      traefik.frontend.rule: Host:transmission.killianhmyd.fr
      traefik.port: 9091
    networks:
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - /home/ubuntu/configs/transmission/config:/config:rw
      - /home/ubuntu/downloads:/downloads:rw

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Paris
    expose:
      - 9117
    labels:
      traefik.backend: jackett
      traefik.frontend.rule: Host:jackett.killianhmyd.fr
      traefik.port: 9117
    networks:
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - /home/ubuntu/configs/jackett/config:/config:rw

  joal:
    image: killianhmyd/joal:latest
    command: |
        '--joal-conf="/data" \
        --spring.main.web-environment="true" \
        --server.port="56098"
    container_name: joal
    expose:
      - 56098
    labels:
      traefik.backend: joal
      traefik.port: 56098
    networks:
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - /home/ubuntu/configs/joal:/data:rw
      - /home/ubuntu/torrents:/data/torrents:rw

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Paris
    expose:
      - 8686
    labels:
      traefik.backend: lidarr
      traefik.port: 8686
    networks:
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - /home/ubuntu:/shared:rw
      - /home/ubuntu/configs/lidarr/config:/config:rw

  plex-server:
    container_name: plex-server
    image: linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1001
      - VERSION=docker
      - HOSTNAME=DockerPlex
    labels:
      traefik.backend: plex
      traefik.port: 32400
    networks:
      - traefik_proxy
    ports:
      - 1900:1900/udp
      - 32410:32410/udp
      - 32469:32469
      - 32413:32413/udp
      - 32412:32412/udp
      - 32414:32414/udp
      - 3005:3005
      - 32400:32400
      - 8324:8324
    restart: unless-stopped
    volumes:
      - /home/ubuntu/configs/plex/transcode:/transcode:rw
      - /home/ubuntu/configs/plex/config:/config:rw
      - /home/ubuntu/configs/plex/data:/data:rw
      - /home/ubuntu/media:/media:rw

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Paris
    expose:
      - 7878
    labels:
      traefik.backend: radarr
      traefik.port: 7878
    networks:
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - /home/ubuntu/configs/radarr/config:/config:rw
      - /home/ubuntu:/shared:rw
  
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Paris
    expose:
      - 8989
    labels:
      traefik.backend: sonarr
      traefik.port: 8989
    networks:
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - /home/ubuntu/configs/sonarr/config:/config:rw
      - /home/ubuntu:/shared:rw
