defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.ping]
  address = ":8082"

  [entryPoints.dashboard]
  address = ":8083"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[[tls.certificates]]
  certFile = "certs/domain.cert"
  keyFile = "certs/to/domain.key"

[ping]
entryPoint = "ping"

[api]
  debug = true
  dashboard = true
  entryPoint = "dashboard"

  [api.statistics]
    recentErrors = 50
